services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlops-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1